from typing import TypedDict, Annotated
# Annotated is used to add metadata to the type, in this case we are using it to specify that the "messages" key 
    # in our state schema should use the add_messages function to add messages to the state. This allows us to easily 
    # update our state with new messages by simply returning a dictionary with the "messages" key and a list of 
    # BaseMessage objects as the value.
from langchain_core.messages import BaseMessage
# BaseMessage is the base class for all messages in LangChain. It has a content attribute which is a string, and can 
    # be extended to include additional attributes if needed (using: BaseMessage(content="message content", additional_attribute="value")).
from langgraph.graph.message import add_messages
# add_messages is a function that allows us to easily add messages to our state. It takes a list of BaseMessage objects 
    # and adds them to the "messages" key in our state schema. This is useful for updating our state with new messages 
    # generated by our nodes.


class MessageGraph(TypedDict):
    """
    The state schema for our graph. In this case, we have a single key "messages" which is a list of BaseMessage objects. 
    The add_messages annotation allows us to use the add_messages function to easily add messages to our state.
    """
    messages: Annotated[list[BaseMessage], add_messages]
     # an example of usage to get the messages from the state would be: message = state["messages"] 
     # an example of usage to update the state by a node return value would be: return {"messages": [HumanMessage(content="new message")]}